title: matt.pictures
email: matt@notuntitled.com
description: > # this means to ignore newlines until "baseurl:"
  These are my photos and stories
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
paginate: 4
encoding: utf-8
